entity.my_entity.collection:
  path: '/admin/content/my_entity'
  defaults:
    _entity_list: 'my_entity'
    _title: 'My Entities'
  requirements:
    _permission: 'administer my entity'

entity.my_entity.add_form:
  path: '/admin/content/my_entity/add'
  defaults:
    _entity_form: 'my_entity.add'
    _title: 'Add My Entity'
  requirements:
    _permission: 'administer my entity'

entity.my_entity.edit_form:
  path: '/admin/content/my_entity/{my_entity}/edit'
  defaults:
    _entity_form: 'my_entity.edit'
    _title_callback: '\Drupal\my_module\Controller\MyEntityController::editTitle'
  requirements:
    _entity_access: 'my_entity.update'

entity.my_entity.delete_form:
  path: '/admin/content/my_entity/{my_entity}/delete'
  defaults:
    _entity_form: 'my_entity.delete'
    _title_callback: '\Drupal\my_module\Controller\MyEntityController::deleteTitle'
  requirements:
    _entity_access: 'my_entity.delete'